version: '3.7'

services:
  mongo:
    image: mongo:latest
    container_name: mongo-for-todo-5
    environment:
      - MONGO_INITDB_DATABASE=${DATABASE_NAME}
      - MONGO_INITDB_ROOT_USERNAME=${DATABASE_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${DATABASE_PASSWORD}
    ports:
      - 27017:27017
    