// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"context"
	"go.mongodb.org/mongo-driver/mongo"
	"todo-level-5/config/db"
	"todo-level-5/pkg/api/handlers"
)

// Injectors from wire.go:

func ProvideTodoHandler() *handlers.TodoHandler {
	client := ProvideClient()
	todoHandler := handlers.NewTodoHandler(client)
	return todoHandler
}

func InjectHandler() *handlers.Handlers {
	todoHandler := ProvideTodoHandler()
	handlersHandlers := handlers.NewHandler(todoHandler)
	return handlersHandlers
}

// wire.go:

func ProvideClient() *mongo.Client {
	return db.Connect(context.Background())
}
