// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"context"
	"go.mongodb.org/mongo-driver/mongo"
	"todo-level-5/config/db"
	"todo-level-5/pkg/api/handlers"
	todo2 "todo-level-5/pkg/application/todo"
	"todo-level-5/pkg/infrastructure/persistence/todo"
)

// Injectors from wire.go:

func ProvideTodoRepo() *todo.TodoRepo {
	client := ProvideClient()
	todoRepo := todo.NewTodoRepo(client)
	return todoRepo
}

func ProvideTodoService() *todo2.TodoService {
	todoRepo := ProvideTodoRepo()
	todoService := todo2.NewTodoService(todoRepo)
	return todoService
}

func ProvideTodoHandler() *handlers.TodoHandler {
	todoService := ProvideTodoService()
	todoHandler := handlers.NewTodoHandler(todoService)
	return todoHandler
}

func InjectHandler() *handlers.Handlers {
	todoHandler := ProvideTodoHandler()
	handlersHandlers := handlers.NewHandler(todoHandler)
	return handlersHandlers
}

// wire.go:

func ProvideClient() *mongo.Client {
	return db.Connect(context.Background())
}
